{
let U={directionType:1,maxDistance:6,startOffset:0,cellSize:1},X,Y,Z,C,cast;
{let P=3.141592653589793,T=6.283185307179586,R=0.017453292519943295,G=57.29577951308232;C={get 11(){let v=1/Math.sqrt(X*X+Y*Y+Z*Z);X*=v;Y*=v;Z*=v},get 12(){Y=Math.atan2(Y,Math.sqrt(X*X+Z*Z));X=Math.atan2(-X,-Z)},get 13(){Y=Math.atan2(Y,Math.sqrt(X*X+Z*Z))*G;X=Math.atan2(-X,-Z)*G},get 21(){X=(X+P)%T;if(X<0){X+=T}X=X-P;let y=Math.cos(X),p=Math.cos(Y);X=-p*Math.sin(X);Y=Math.sin(Y);Z=-p*y},get 22(){X=(X+P)%T;if(X<0){X+=T}X=X-P},get 23(){X=(X+P)%T;if(X<0){X+=T}X=X-P;X*=G;Y*=G},get 31(){X=(X+180)%360;if(X<0){X+=360}X-=180;X*=R;Y*=R;let y=Math.cos(X),p=Math.cos(Y);X=-p*Math.sin(X);Y=Math.sin(Y);Z=-p*y},get 32(){X=(X+180)%360;if(X<0){X+=360}X-=180;X*=R;Y*=R},get 33(){X=(X+180)%360;if(X<0){X+=360}X-=180}}}
{let F=1e9,a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0,n=0,o=0,p=0,q=0,r=0,s=0,t=0,u=0,v=0,w=0;cast=(P,D,T,M,O,L,I)=>{a>>=I===true;b-=c;if(a===0){X=D[0];Y=D[1];Z=D[2];let A=T|0;if(A<1|A>3){A=U.directionType}C[A+"1"];d=X;e=Y;f=Z;let B=M;if(!(B>0)){B=U.maxDistance}let E=O;if(E===undefined|E===null){E=U.startOffset}let G=L;if(!(G>0)){G=U.cellSize}g=E;h=P[0]+d*E;i=P[1]+e*E;j=P[2]+f*E;k=(d>0)-(d<0);l=(e>0)-(e<0);m=(f>0)-(f<0);let H=d*k,J=e*l,K=f*m,N=+(H===0),Q=+(J===0),R=+(K===0);n=G/(H+N);o=G/(J+Q);p=G/(K+R);q=Math.floor(h/G);r=Math.floor(i/G);s=Math.floor(j/G);if(N){t=F}else{t=((q+(k+1>>1))*G-h)/d}if(Q){u=F}else{u=((r+(l+1>>1))*G-i)/e}if(R){v=F}else{v=((s+(m+1>>1))*G-j)/f}let S=G*1e-9;if(t===0){t+=S}if(u===0){u+=S}if(v===0){v+=S}w=B+S;b=0;a=1}if(a===1){c=1;let A=k,B=l,E=m,G=n,H=o,J=p,K=q,N=r,Q=s,R=t,S=u,V=v,W=w,x,y,z,$,_,__;do{b++;q=K;r=N;s=Q;t=R;u=S;v=V;x=R<S&R<V;y=S<=V&1-x;z=1-x-y;$=R*x+S*y+V*z;K+=A*x;N+=B*y;Q+=E*z;R+=G*x;S+=H*y;V+=J*z;_=api.getBlockId(K,N,Q);__=$<=W}while(!_&__);let _x=-A*x,_y=-B*y,_z=-E*z;c=0;a=0;return{blockId:_,position:[K,N,Q],normal:[_x,_y,_z],adjacent:[K+_x,N+_y,Q+_z],point:[h+d*$,i+e*$,j+f*$],distance:$+g,offsetDistance:$,steps:b,inRange:__}}}}
let offsetPosition=(P,D,T,O)=>{let f=T|0;if(f<1|f>3){f=U.directionType}X=D[0];Y=D[1];Z=D[2];C[f+"1"];let o=O;if(o===undefined|o===null){o=U.startOffset}return[P[0]+X*o,P[1]+Y*o,P[2]+Z*o]};
let maxDistancePosition=(P,D,T,M,O)=>{let f=T|0;if(f<1|f>3){f=U.directionType}X=D[0];Y=D[1];Z=D[2];C[f+"1"];let m=M;if(!(m>0)){m=U.maxDistance}let o=O;if(o===undefined|o===null){o=U.startOffset}let t=m+o;return[P[0]+X*t,P[1]+Y*t,P[2]+Z*t]};
let convertDirection=(R,I,O)=>{let i=I|0;if(i<1|i>3){i=U.directionType}let o=O|0;if(o<1|o>3){o=U.directionType}X=R[0];Y=R[1];Z=R[2];C[""+i+o];if(o===1){return[X,Y,Z]}else{return[X,Y]}};
globalThis.BR=Object.seal({default:U,cast,convertDirection,offsetPosition,maxDistancePosition})}
S={t:{},g:{},c:0,o:0,i:0,d:{get false(){let t=S.t[S.c];do{let e=3*S.i;[t[e],S=>S][+(t[e+2]<S.g[t[e+1]])]()}while(++S.i<t.length/3);delete S.t[S.c],S.i=0}},run(t,e,l){let c=S.c-~e-1,g=S.t[c]=[S.t[c],[]][+!S.t[c]],i=g.length;g[i]=t,g[i+1]=[l,"0"][+!l],g[i+2]=S.o++},stop(t){S.g[t]=S.o++}};
tick=()=>{S.d[!S.t[S.c]],S.c++;};
function smoothTerrainWE_Batched(t,e,{passes:l=3,readPerTick:n=200,writePerTick:r=100,smoothStrength:o=.3}={}){let _=e[0]-t[0]+1;e[1],t[1];let f=e[2]-t[2]+1,$=_*f,i=new Int16Array($);function u(t,e){return e*_+t}let c=[];for(let h=0;h<_;h++)for(let s=0;s<f;s++)c.push([h,s]);function a(){for(let r=0;r<n&&c.length>0;r++){let[u,h]=c.shift();for(let s=e[1];s>=t[1];s--)if(isSolid(api.getBlockId(t[0]+u,s,t[2]+h))){var k,p;i[k=u,(p=h)*_+k]=s;break}}c.length>0?S.run(a,1):S.run(()=>(function t(e){let n=new Int16Array($);for(let r=0;r<$;r++)n[r]=i[r];for(let u=1;u<_-1;u++)for(let c=1;c<f-1;c++){var h,s,a,k,p,d,m,v,b,w;let T=(h=u,(s=c)*_+h),A=i[T],E=(i[a=u-1,(k=c)*_+a]+i[p=u+1,(d=c)*_+p]+i[m=u,(v=c-1)*_+m]+i[b=u,(w=c+1)*_+b]+A)/5,G=E-A,I=Math.sign(G)*Math.min(Math.abs(G)*o,1);n[T]=A+I}for(let W=0;W<$;W++)i[W]=n[W];e<l?S.run(()=>t(e+1),1):function t(){for(let e=0;e<_;e++)for(let l=0;l<f;l++){var n,r;g.push([e,l,i[n=e,(r=l)*_+n]])}S.run(B,1)}()})(1),1)}S.run(a,1);let g=[];function B(){for(let l=0;l<r&&g.length>0;l++){let[n,o,_]=g.shift();for(let f=e[1];f>_;f--)api.setBlock([t[0]+n,f,t[2]+o],"Air");for(let $=_;$>=t[1];$--)api.setBlock([t[0]+n,$,t[2]+o],"Grass Block")}g.length>0?S.run(B,1):console.log("✔ Terrain complete!")}}function isSolid(t){return 0!==t&&1!==t&&126!==t&&1491!==t}
function placeSphereBatched(e,t,l,n=5){let[f,o,r]=e,h=[];for(let c=-t;c<=t;c++)for(let u=-t;u<=t;u++)for(let i=-t;i<=t;i++)c*c+u*u+i*i<=t*t&&h.push([f+c,o+u,r+i]);function p(){for(let e=0;e<n&&h.length>0;e++){let t=h.shift();api.setBlock(t,l)}h.length>0&&S.run(p,1)}S.run(p,1)}
function parseBlockType(e,t){let n=e[t],r=parseInt(n,10);if(!isNaN(r))return{type:api.blockIdToBlockName(r),nextIndex:t+1};if(n.startsWith('"')){let l=n,p=t+1;for(;p<e.length&&(l+=" "+e[p],!e[p].endsWith('"'));)p++;let c=l.replace(/^"/,"").replace(/"$/,"");return{type:c,nextIndex:p+1}}return{type:n,nextIndex:t+1}}

playerCommand=(t,e)=>{let s=e.split(" "),i=api.getHeldItem(t);if("brush"===s[0]&&i){let o=s[1];if("sphere"===o&&s.length>=5){let r=parseInt(s[2],10),u=api.getSelectedInventorySlotI(t),m=parseBlockType(s,3),a=m.type,c=parseInt(s[4],10);return api.setItemSlot(t,u,i.name,1,{customDisplayName:`${i.name} radius ${r}/ blockType ${a}`||"",customDescription:i.attributes.customDescription||"",customAttributes:{size:r,blocktype:a,speed:c,mode:"sphere"}}),!0}if("smooth"===o&&s.length>=4){let n=api.getSelectedInventorySlotI(t),b=parseInt(s[2],10)||5,p=parseInt(s[3],10),l=parseInt(s[4],10)||2,$=parseFloat(s[5])||.2;return api.setItemSlot(t,n,i.name,1,{customDisplayName:`${i.name} smooth area ${b} \xd7 ${b} `||"",customDescription:i.attributes.customDescription||"",customAttributes:{size:b,speed:p,passes:l,strength:$,mode:"smooth"}}),!0}}},onPlayerClick=(t,e)=>{let s=api.getHeldItem(t);if(!s||!s.attributes||!s.attributes.customAttributes.mode)return;let i=BR.cast(api.getPosition(t),api.getPlayerFacingInfo(t).dir,200,100,1,0);if(i){if("sphere"===s.attributes.customAttributes.mode){let o=s.attributes.customAttributes.size||5,r=s.attributes.customAttributes.blocktype||"Grass Block",u=s.attributes.customAttributes.speed||100;placeSphereBatched(i.position,o,r,u)}else if("smooth"===s.attributes.customAttributes.mode){let m=s.attributes.customAttributes.size||5,a=s.attributes.customAttributes.speed||100,c=s.attributes.customAttributes.passes||2,n=s.attributes.customAttributes.strength||.2,b=i.position[1]+m,p=i.position[1]-m,l=[i.position[0]-(m/2|0),Math.max(0,p),i.position[2]-(m/2|0)],$=[i.position[0]+(m/2|0),Math.min(255,b),i.position[2]+(m/2|0)];smoothTerrainWE_Batched(l,$,{passes:c,readPerTick:a,writePerTick:a,smoothStrength:n})}}};
