m=api.attemptSpawnMob("NPC",...thisPos,{name:"Guard NPC",variation:"default"})
api.setMobSetting(m,"maxHealth",100)
api.setHealth(m,100)
api.setMobSetting(m,"heldItemName","Knight Sword")
api.setMobSetting(m,"attackItemName","Knight Sword")
api.setMobSetting(m,"attackDamage",55)
api.setMobSetting(m,"onDeathAura",405)
api.setMobSetting(m,"chaseRadius",64)
api.setMobSetting(m,"territoryRadius",64)
api.setMobSetting(m,"hostilityRadius",64)
api.setMobSetting(m,"armour",{Helmet:{itemName:"Iron Helmet"},Chestplate:{itemName:"Iron Chestplate"},Gauntlets:{itemName:"Iron Gauntlets"},Leggings:{itemName:"Iron Leggings"},Boots:{itemName:"Iron Boots"}})
api.applyEffect(m,"Damage Reduction",null,{inbuiltLevel:5})
